### ISSUE TITLE
AllowInput for DatePicker

### ISSUE THREAD

**Issue by nagytam** [SamProf/MatBlazor#180]
The DatePicker control does NOT support direct input currently, however the underlying component would support it. See https://flatpickr.js.org/options/, allowInput option.
Please add this allowInput parameter as well.

**Comment by nagytam** [comment]
Is this solved by the commit 'Add more flatpickr options' https://github.com/SamProf/MatBlazor/commit/d89ed5708017a8a9090f369179cc0a991f965502 ?

**Comment by djinnet** [comment]
Well, it should be solved. I haven't testing the allowInput option yet, but you can try to get the newest update with nuget and try that out.

I have only added the basic options (boolean options and string options). 
The options that required an funtion, numbers or array aren't added yet because I don't know how to add them without having ugly workaround for these options. 

However I would love to see someone who got an clever idea to deal with these advanced options. :)

**Comment by lindespang** [comment]
Hello! This has been solved and it's now possible to use direct input. Check demo pages for examples:
https://www.matblazor.com/DatePicker
