### ISSUE TITLE
CSS base?

### ISSUE THREAD

**Issue by rogeralsing** [SamProf/MatBlazor#222]
Maybe this is already described somewhere but I couldn't find it.

Does MatBlazor build on some existing Material CSS kit (e.g. Materialize) or are all styles unique to MatBlazor?

**Comment by Redeye51** [comment]
I have a related question. I'm trying to override the base CSS because the menu items text color after selection is the same as the background color. I've attached pictures of the before and after click. Also attached the code. All very simple and should work.

![menu-before](https://user-images.githubusercontent.com/1115483/64039070-a2a1bc80-cb0e-11e9-9199-0fdf20bb37d8.png)
![menu-after](https://user-images.githubusercontent.com/1115483/64039072-a59cad00-cb0e-11e9-80b8-0a92b06f4ce1.png)
![menu-code](https://user-images.githubusercontent.com/1115483/64039074-a7ff0700-cb0e-11e9-829e-81cdb0935212.png)

**Comment by Redeye51** [comment]
I was able to override the style using the following.

.app-sidebar {
    color:#fff
}
    .app-sidebar .mdc-list-item--selected {
        border-left: solid 3px rgba(255, 255, 255, .5);
        color: #fff !important;
    }

**Comment by gitbugreport** [comment]
Would be nice if we have CSS in separate file or SASS file instead of a style tag in the body.

**Comment by endstreet** [comment]
@gitbugreport Good Idea!

**Comment by RonPeters** [comment]
I just created a pull request #370 to address this
