### ISSUE TITLE
Is RefBack broken?

### ISSUE THREAD

**Issue by dga711** [SamProf/MatBlazor#236]
I wondered how RefBack references are always null for me.

When debugging MatBlazor I found that imo it can't work. On the other side it is such basic functionality so that I can't believe it doesn't work. 

See https://github.com/SamProf/MatBlazor/blob/master/src/MatBlazor/Components/Base/BaseMatDomComponent.cs#L29

Here RefBack is never set because it is always null when Ref gets set. I think BuildRenderTree evaluates the RefBack assignment later? Therefore RefBack's value is also always null.

Can you verify that?

**Comment by SamProf** [comment]
RefBack mechanism works.

It's needed because we need to have reference before component is rendered, but use after rendered.

Here is example how it works. https://blazorfiddle.com/s/zwicdi70

You can also read my article about this theme https://www.samprof.com/2019/06/03/blazor-forwardref

If you have some question or propositions - you are welcome.
