### ISSUE TITLE
MatBlazorSwitchT - Missing some implementations for nullable types

### ISSUE THREAD

**Issue by YBAZAN** [SamProf/MatBlazor#365]
First of all, thank you for your amazing library. Very useful in my project.

I noticed that when I bind `MatTextField` to a `int?` property, it fails at runtime with a `NullReferenceException`.

After looking deeper, I realized that you don't propose any implementation for `int?` in your class `MatBlazorSwitchT`. It's the same for `byte`, `float` and `double`.

Not a big deal to add I hope...

**Comment by fire-birdie** [comment]
I ran into this problem while trying to bind `MatNumericUpDownField` to an `int?` field. Looking at the 2.0.0 release notes makes it seem like the decision to omit support for non-decimal nullable types was intentional, but I can't figure out why. I'll prepare a PR to add support for the other primitive types, I just hope it doesn't break anything...
