### ISSUE TITLE
Rtl support

### ISSUE THREAD

**Issue by j209** [SamProf/MatBlazor#381]
hi
any plan for rtl support

**Comment by zandiarash** [comment]
> 
> 
> hi
> any plan for rtl support

I'm also looking for answer...

**Comment by T-Alkathiri** [comment]
I am also having the same question
Please some one adapt this.
Thank you very much.

**Comment by zandiarash** [comment]
This is the solution
```
<body dir="rtl">
</body>
```

@T-Alkathiri  - @j209

**Comment by T-Alkathiri** [comment]
Thank you very much
It works good for me.

**Comment by HarelM** [comment]
I looked at the stack overflow example, and I'm not sure this is fully qualified for RTL support.
I'm using Angular material with flexbox layout, they are using the terminology of `start` and `end` instead of `left` and `right`.
For example `grid-align-end` and not `grid-align-right`. This allows to design a site that can be switched on-the-fly from RTL to LTR as can be seen in my site here (language button is on the right side panel):
https://israelhiking.osm.org.il/
Angular-material is checking in the css the rtl property and does some logic according to it.
Full support for RTL is not easy and I'm not sure it is fully supported here.
For example in the SO screenshot the "hello world!" text should be aligned right and not aligned left with the text in rtl mode only, I believe.
I'll be happy to helpout progressing this or at least help testing if I decide to migrate my site to blazor, which I'm currently thinking about.
I'll be happy to provide counseling support in terms of correctness in either way as I think RTL is an important feature to a framework like this one.
In any case, I think this issue should be re-opened or I can open specific issues when I encounter a control that doesn't behave as expected assuming I'll be migrating to blazor.
Let me know which is preferred. :-) 
Thanks again for all the hard work!
