### ISSUE TITLE
Why start names with “Mat”?

### ISSUE THREAD

**Issue by kristof12345** [SamProf/MatBlazor#505]
Hi!

The react material ui library just uses component names without “Mat”. Is there a specific reason you choose to add this prefix?

**Comment by EduVencovsky** [comment]
I don't know the real reason why it starts with `Mat` but I will share my case.

In my company project, they use Telerik for Blazor, which is good, but the problem is that Telerik components don't have any prefix, so if I want to create a component with the same name as telerik component, I will have class name conflicts and in some cases you need to do alot of

    using Something = NameSpace.Something

And this is very annoying.

Now Imagine if you are using MatBlazor with Telerik and MatBlazor components don't start with `Mat`, they are just the name of the component. In that case you will have a conflict with alot of components (e.g. Button) if you use both libraries in the same class.

So starting with some prefix is actually very good and prevent name conflicts.

**Comment by enkodellc** [comment]
@kristof12345  the naming convention as described by @EduVencovsky is correct and carried though most Material Design sets:

- mdc - https://material.io/
- mat - Angular Material https://material.angular.io/
- mdl - Material Design Lite

https://medium.com/@drublic/css-naming-conventions-less-rules-more-fun-12af220e949b
