### ISSUE TITLE
Unable to filter by column name MatTable

### ISSUE THREAD

**Issue by dortiz750** [SamProf/MatBlazor#534]
Hello,

I am new to front end development. I am attempting to use a MatTable component with filter by column name enabled. The data I am attempting to filter is static as shown within the fiddler link below. Can someone please point me in to the correct direction as what I am doing wrong to filter by the column "Name"? 
 
https://blazorfiddle.com/s/e8n1udqu

Additional context: I am using server side Blazor.

**Comment by lindespang** [comment]
Hi!

Thanks for reporting.

The filter in your example works for me, I type Volkswagen => Only Volkswagen rows appear.
I guess that your issue is that the placeholder text looks weird in the filter box?
![image](https://user-images.githubusercontent.com/36196344/81387461-07d69480-9117-11ea-8b1d-afd401a126a5.png)

If that's the case then I would suggest you edit your title (or I will do it for you) and we'll link together the related issues (there are a few different controls with this issue)  so it's clear that this issue is UI placeholder bug and not problems with filtering.

If it isn't, then please give better example on what you expect to happen in your fiddle!

**Comment by dortiz750** [comment]
Hello,

Thank you for the prompt reply. The issue I am encountering is post entering a string value which should match a string value within the desired column. For example, as shown below I entered the full string "Volkswagen" and the filter did not remove none matching values. I am wondering if there may be a conflict with other scripts used within my project, any thoughts?

![image](https://user-images.githubusercontent.com/35080686/81411290-2c7b3e00-9110-11ea-9dfa-689b3dfd67ba.png)

**Comment by lindespang** [comment]
Very hard for me to tell unfortunately, maybe you can try to recreate some of the things around it on www.blazorfiddle.com ? Or strip your project piece by piece until it starts working and get back with the results

**Comment by dortiz750** [comment]
Interestingly I tested the filter functionality binding data via API ref vs static and that worked just fine, which is the desired outcome anyway. I really appreciate the support! 

Have a good weekend!

**Comment by lindespang** [comment]
Glad to hear it worked out!:) Closing issue.
