### ISSUE TITLE
MatTable should not assume that an Http client will be registered in the DI container

### ISSUE THREAD

**Issue by StevenRasmussen** [SamProf/MatBlazor#67]
The MatTable component has an @inject statement requiring an HttpClient to be registered in the DI container.  In my instance, I am querying a DB context directly for items and so I don't need an HttpClient to retrieve any data.  Also, for anyone loading static data they would also not need an HttpClient.

**Comment by enkodellc** [comment]
@StevenRasmussen  I think I understand the issue you are addressing but you might want to clarify it a bit for me. Is it that your application doesn't use the HttpClient at all AND when you want to use MatTable it errors out if you do not include @using HttpClient? If that is the case please provide your code or examples.

I ran two tests using default Blazor applications.  From VS, install Web Applications "Blazor (ASP.NET Core Hosted)" and "Blazor (client-side)"  Then used the first basic example with the static data class cars and in both cases I did not get any errors or warnings for missing "HttpClient" dependency. So my application did not have to include "@using HttpClient"

If your issue is that the MatBlazor is bloated because it requires HttpClient then I would have to defer that to @SamProf.

Either way I will need more information on your specific situation to address it, Thanks.

**Comment by StevenRasmussen** [comment]
@enkodellc - thanks for the reply!  Your first assumption was correct.  Currently I don't use an HttpClient at all.  I may need one down the future but for now I don't.  I just started this project and used the "Blazor (Server Side)" template found in Asp.Net Core 3.0 Preview 4.  To resolve the error I simply added an HttpClient to the DI container in the startup method like this:

`services.AddScoped<HttpClient>();`

**Comment by SamProf** [comment]
@enkodellc I dont really check MatTable code and API.
I just think that MatTable should work with abstract Storage, that can be only client-side for example or server side or custom.... it;s just my opinion. I will check your MatTable later.

**Comment by enkodellc** [comment]
He is correct that if you have a "Blazer (server-side)" project it needs. `services.AddScoped<HttpClient>();`
Personally I think that most people will be doing client-side. Server side will take a fairly large toll on the server for an application with significant traffic.  It is a minor issue that should be noted in the MatTable page. Just my opinion. Of course if this is not satisfactory anyone can fork it and use the code on their own.

The API portion is tested fine but I have not tested the API paging, sorting and filtering portion.

**Comment by SamProf** [comment]
Related of #166
