### ISSUE TITLE
General library design

### ISSUE THREAD

**Issue by prajaybasu** [SamProf/MatBlazor#69]
It would be nice if MatBlazor was built in a way that we could install the Nuget package only for the component we need, like how imports work in React. Right now installing MatBlazor in my projects imports all components in my project's Components folder and it gets a bit crowded even if I am using only a single component from MatBlazor.

**Comment by IvanJosipovic** [comment]
You shouldnt see the MatBlazor components in your project since this pr, https://github.com/SamProf/MatBlazor/pull/64

**Comment by prajaybasu** [comment]
> You shouldnt see the MatBlazor components in your project since this pr, #64
> Are you on the lastest version?

Ah sorry, I forgot to update the package version in one of my projects, it is fixed now.

But I still think that the components should be packaged as separate libraries, so that I can update them separately and so that you can build upon existing components without making the main library too heavy (example: OData support proposal).

**Comment by SamProf** [comment]
Now, its difficult to separate every component in separate project.
Matbe it's possible, but I think not now.

I undastand benefits, but it would be not easy to use MatBlazor if every component in another nuget package.
But some of components will be available as standalone libraries.

I think after real release of Blazor (and MatBlazor) we can think about it.

**Comment by jorgy343** [comment]
For the record I am against creating tens of nuget packages. Currently, .net is fundamentally different from JavaScript when it comes to how packages are handled.

**Comment by SamProf** [comment]
Soon I will add some MatBlazor-related packages, that's potentially will be another nuget-package.
But main MatBlazor will be monolithic now.
For server-side Blazor it's not a big sense  to have many libraries.
For client-side Blazor I think Blazor will have optimizer, what will remove unused components from build.

Maybe we will return to this question sometimes later, but now this issue looks resolved. 
If you think otherwise, feel free,  just re-open the issue.
